# SQL DATABASE CONFIGURATION #
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pwaProject?useSSL=false
        username: root
        password: *************
        validationQuery: SELECT 1
        testWhileIdle: true
    jpa:
        show-sql: true
        hibernate:
            # line fo create and update the database
            #ddl-auto: create-drop  
            # line to add in the database to don't alter it or / drop 
            ddl-auto: update 
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            
# API Rest #
    data:
       rest:
           basePath: /api
           
facebook:
    app:
        id: 1821624328073601
        secret: 6af48180a320e2a17f6d17eedffb6f20

            
#spring:
#    datasource:
#        url: jdbc:h2:./database
#    jpa:
#       hibernate: 
#            ddl-auto: create-drop


# SSL Configuration #
server:
  port:
    8043
  ssl:
    enabled:
      true
    keyStoreType:
      PKCS12
    key-store:
      keystore.p12
    key-store-password:
      socialNetworkUJM
  http:
    port:
      8080



