# SQL DATABASE CONFIGURATION #
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/pwaDatabase?useSSL=false
        username: pwaDatabase
        password: lFlc1JJVyRzSDZDv
        validationQuery: SELECT 1
        testWhileIdle: true
    jpa:
        show-sql: true
        hibernate:
            # line fo create and update the database
            #ddl-auto: create-drop  
            # line to add in the database to don't alter it or / drop 
            ddl-auto: update 
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

facebook:
    app:
        id: 1821624328073601
        secret: 6af48180a320e2a17f6d17eedffb6f20

            
#spring:
#    datasource:
#        url: jdbc:h2:./database
#    jpa:
#       hibernate: 
#            ddl-auto: create-drop


# SSL Server Configuration #
#server:
#   port:8443
#   ssl:
#       keystore: keystore.p12
#       key-store-password: socialNetworkUJM
#       keyStoreType: PKCS12
#       keyAlias: socialNetwork

# API Rest #
    data:
       rest:
           basePath: /api

