# SQL DATABASE CONFIGURATION #
spring:
    datasource:
<<<<<<< HEAD
        url: jdbc:mysql://localhost:3306/pwaproject?useSSL=false
        username: root
        password: root
=======
        url: jdbc:mysql://127.0.0.1:3306/pwaProject?useSSL=false
        username: root
        password: ****
>>>>>>> bcd824107f10f217909eabe4870cd596fc8ade52
        validationQuery: SELECT 1
        testWhileIdle: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    social:
        facebook:
            appId: 1821624328073601
            appSecret: 6af48180a320e2a17f6d17eedffb6f20
            
#spring:
#    datasource:
#        url: jdbc:h2:./database
#    jpa:
#       hibernate: 
#            ddl-auto: create-drop


# SSL Server Configuration #
#server:
#   port:8443
#   ssl:
#       keystore: keystore.p12
#       key-store-password: socialNetworkUJM
#       keyStoreType: PKCS12
#       keyAlias: socialNetwork

# API Rest #
#spring: 
#   data:
#       rest:
#           basePath: /api
